<a href="https://colab.research.google.com/github/harshchamp/IOT_Sensor/blob/main/Smart_Manufacturing_IoT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "smart_manufacturing_data.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "ziya07/smart-manufacturing-iot-cloud-monitoring-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_5061/2043885261.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to /root/.cache/kagglehub/datasets/ziya07/smart-manufacturing-iot-cloud-monitoring-dataset/versions/1/smart_manufacturing_data.csv...

100%|██████████| 6.93M/6.93M [00:00<00:00, 71.6MB/s]

First 5 records:              timestamp  machine_id  temperature  vibration  humidity  \
0  2025-01-01 00:00:00          39        78.61      28.65     79.96
1  2025-01-01 00:01:00          29        68.19      57.28     35.94
2  2025-01-01 00:02:00          15        98.94      50.20     72.06
3  2025-01-01 00:03:00          43        90.91      37.65     30.34
4  2025-01-01 00:04:00           8        72.32      40.69     56.71

   pressure  energy_consumption  machine_status  anomaly_flag  \
0      3.73                2.16               1             0
1      3.64                0.69               1             0
2      1.00                2.49               1             1
3      3.15                4.96               1             1
4      2.68                0.63               2             0

   predicted_remaining_life     failure_type  downtime_risk  \
0                       106           Normal            0.0
1                       320           Normal            0.0
2                        19           Normal            1.0
3                        10           Normal            1.0
4                        65  Vibration Issue            0.0

   maintenance_required
0                     0
1                     0
2                     1
3                     1
4                     1

In [ ]:
df

,timestamp,machine_id,temperature,vibration,humidity,pressure,energy_consumption,machine_status,anomaly_flag,predicted_remaining_life,failure_type,downtime_risk,maintenance_required
0,2025-01-01 00:00:00,39,78.61,28.65,79.96,3.73,2.16,1,0,106,Normal,0.0,0
1,2025-01-01 00:01:00,29,68.19,57.28,35.94,3.64,0.69,1,0,320,Normal,0.0,0
2,2025-01-01 00:02:00,15,98.94,50.20,72.06,1.00,2.49,1,1,19,Normal,1.0,1
3,2025-01-01 00:03:00,43,90.91,37.65,30.34,3.15,4.96,1,1,10,Normal,1.0,1
4,2025-01-01 00:04:00,8,72.32,40.69,56.71,2.68,0.63,2,0,65,Vibration Issue,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2025-03-11 10:35:00,3,71.47,54.34,46.72,1.83,3.05,1,0,313,Normal,0.0,0
99996,2025-03-11 10:36:00,23,87.23,34.99,33.84,4.67,4.47,1,0,439,Normal,0.0,0
99997,2025-03-11 10:37:00,10,93.01,51.79,64.28,4.04,3.62,1,1,30,Normal,1.0,1
99998,2025-03-11 10:38:00,47,84.41,22.35,35.18,2.88,2.37,1,0,487,Normal,0.0,0
99999,2025-03-11 10:39:00,32,73.53,67.09,74.35,2.15,2.50,1,0,446,Normal,0.0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   timestamp                 100000 non-null  object
 1   machine_id                100000 non-null  int64
 2   temperature               100000 non-null  float64
 3   vibration                 100000 non-null  float64
 4   humidity                  100000 non-null  float64
 5   pressure                  100000 non-null  float64
 6   energy_consumption        100000 non-null  float64
 7   machine_status            100000 non-null  int64
 8   anomaly_flag              100000 non-null  int64
 9   predicted_remaining_life  100000 non-null  int64
 10  failure_type              100000 non-null  object
 11  downtime_risk             100000 non-null  float64
 12  maintenance_required      100000 non-null  int64
dtypes: float64(6), int64(5), object(2)
memory usage: 9.9+ MB

In [ ]:
df.describe()

,machine_id,temperature,vibration,humidity,pressure,energy_consumption,machine_status,anomaly_flag,predicted_remaining_life,downtime_risk,maintenance_required
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,25.499330,75.015625,50.012270,54.995401,3.000405,2.747064,1.002050,0.089160,234.269160,0.089155,0.196970
std,14.389439,10.031884,14.985444,14.437960,1.152399,1.297865,0.446193,0.284976,150.063062,0.284961,0.397711
min,1.000000,35.550000,-17.090000,30.000000,1.000000,0.500000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,13.000000,68.267500,39.970000,42.520000,2.000000,1.630000,1.000000,0.000000,97.000000,0.000000,0.000000
50%,25.000000,75.060000,49.960000,54.980000,3.010000,2.740000,1.000000,0.000000,230.000000,0.000000,0.000000
75%,38.000000,81.750000,60.100000,67.500000,4.000000,3.870000,1.000000,0.000000,365.000000,0.000000,0.000000
max,50.000000,121.940000,113.800000,80.000000,5.000000,5.000000,2.000000,1.000000,499.000000,1.000000,1.000000